baseURL: "http://geobasinas.com"
title: Geobasinas
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Geobasinas
  description: ""
  keywords: [Blog, Geobasinas]
  author: Me
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon.ico"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Geobasinas
    subtitle: "Welcome to my blog"
    imageUrl: "img/profile.png"
    imageWidth: 192
    imageHeight: 192



  # home-info mode
  homeInfoParams:
    Title: "Hi there!"
    Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/geobasinas"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: Blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: About
      name: About
      url: /about/
      weight: 20
    - identifier: Contact
      name: Contact
      url: /contact/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
  goldmark:
        renderer:
            unsafe: true
    